# Generated by Django 2.1.7 on 2019-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('PL', 'PL'), ('EN', 'EN')], default='PL', max_length=2),
        ),
    ]
