# Generated by Django 2.2.6 on 2019-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190514_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
